# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""How many federations are both well covered AND measured precisely enough?

This is the shape-of-the-project query. Two independent filters, applied to the
184 senior squads in data/overlap.csv:

  coverage   windowed redlink rate below 30%. The diagnostic found the
             redlink-vs-share relationship is a cliff, not a gradient: below 30%
             the rank correlation is near zero (men -0.05, women -0.16), above
             it it bites (men -0.27, women -0.43). So 30% is where a measured
             share stops being confounded by article coverage, not an arbitrary
             cut. Reported at 25% and 35% too, so the answer is not an artifact
             of the exact threshold.

  precision  the federation appeared in at least K of its 8 in-window youth
             editions. This is NOT a bias correction. A 21-player pool is not
             evidence of poor conversion, it is almost no evidence at all --
             Switzerland's 13% in w2023 is a sample of 21 and Japan's 70% is a
             sample of 147, and the current metric reports the imprecise one as
             a low score. Sampling noise rendered as a point estimate.

The intersection decides what this project is. A dozen surviving federations
means case studies; sixty means a statistical finding worth curating 184
finishes for.

It also decides whether RSSSF is worth doing, which is a question about the
INTERSECTION and not about the tail on its own. RSSSF closes the coverage
filter for badly-covered federations. If those same federations are already
removed by the precision filter, it rescues nobody. The rescue count reported
here is exactly: federations failing coverage but passing precision.

    uv run scripts/intersection.py
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
REPORTS = ROOT / "reports"

EDITIONS = [("w", 2019), ("w", 2023), ("m", 2010), ("m", 2014), ("m", 2018), ("m", 2022)]
REDLINK_CUTS = [0.25, 0.30, 0.35]
EDITION_CUTS = [4, 5, 6]
MAIN_CUT = 0.30


class Squad:
    __slots__ = ("team", "gender", "year", "share", "redlink", "pool", "n_ing", "size")

    def __init__(self, r: dict, n_ing: int):
        self.team = r["team"]
        self.gender = r["gender"]
        self.year = int(r["year"])
        self.size = int(r["squad_size"])
        self.share = float(r["share_youth_alumni"]) if r["share_youth_alumni"] else None
        self.pool = int(r["n_youth_pool"])
        cov = r["youth_coverage_rate"]
        self.redlink = 1.0 - float(cov) if cov else None
        self.n_ing = n_ing

    @property
    def ed(self) -> str:
        return f"{self.gender}{self.year}"


def load() -> list[Squad]:
    with (DATA / "window_coverage_rates.csv").open(newline="", encoding="utf-8") as fh:
        ing = {(r["team"], r["gender"], int(r["senior_year"])): int(r["n_editions_ingested"])
               for r in csv.DictReader(fh)}
    with (DATA / "overlap.csv").open(newline="", encoding="utf-8") as fh:
        return [Squad(r, ing[(r["team"], r["gender"], int(r["year"]))])
                for r in csv.DictReader(fh)]


def covered(s: Squad, cut: float) -> bool:
    return s.redlink is not None and s.redlink < cut


def precise(s: Squad, k: int) -> bool:
    return s.n_ing >= k


def main() -> int:
    squads = load()
    usable = [s for s in squads if s.share is not None and s.redlink is not None]
    out: list[str] = []

    out.append("# Intersection: well-covered AND precisely-measured federations\n")
    out.append("Generated by `uv run scripts/intersection.py` from `data/overlap.csv`")
    out.append("and `data/window_coverage_rates.csv`. No coverage scaling, no imputation,")
    out.append("no ranking. Counts only.\n")
    out.append(f"184 senior squads; {len(usable)} have both a defined share and a defined")
    out.append("coverage rate. The other 32 appeared in none of their 8 in-window youth")
    out.append("editions, so they fail the precision filter at every threshold anyway.\n")

    # ---------------------------------------------------------------- headline
    out.append("## Surviving squads, per senior edition\n")
    out.append("Cell = squads passing both filters. A squad is one (federation, senior")
    out.append("edition) pair; a federation can survive in some editions and not others.\n")
    for cut in REDLINK_CUTS:
        marker = "  <- headline" if cut == MAIN_CUT else ""
        out.append(f"\n### redlink rate < {cut:.0%}{marker}\n")
        out.append("| edition | squads | defined | cov only | " +
                   " | ".join(f"cov AND >={k} eds" for k in EDITION_CUTS) + " |")
        out.append("|---|---|---|---|" + "---|" * len(EDITION_CUTS))
        for gender, year in EDITIONS:
            sub = [s for s in squads if s.gender == gender and s.year == year]
            d = [s for s in sub if s.share is not None and s.redlink is not None]
            c = [s for s in d if covered(s, cut)]
            cells = " | ".join(str(sum(1 for s in c if precise(s, k))) for k in EDITION_CUTS)
            out.append(f"| {gender}{year} | {len(sub)} | {len(d)} | {len(c)} | {cells} |")
        c_all = [s for s in usable if covered(s, cut)]
        cells = " | ".join(str(sum(1 for s in c_all if precise(s, k))) for k in EDITION_CUTS)
        out.append(f"| **pooled (squads)** | 184 | {len(usable)} | {len(c_all)} | {cells} |")
        uniq = " | ".join(
            str(len({s.team for s in c_all if precise(s, k)})) for k in EDITION_CUTS)
        out.append(f"| **distinct federations** | — | {len({s.team for s in usable})} | "
                   f"{len({s.team for s in c_all})} | {uniq} |")

    # ---------------------------------------------------- which filter is binding
    out.append("\n## Which filter is doing the work\n")
    out.append(f"At the {MAIN_CUT:.0%} coverage cut. 'Rescued by RSSSF' is the count that")
    out.append("decides whether RSSSF is worth doing: squads that fail coverage but pass")
    out.append("precision, i.e. the ones a supplementary source would actually add to the")
    out.append("usable set. Squads failing precision are not rescued by any source --")
    out.append("their federation did not play enough in-window youth editions to measure.\n")
    out.append("| K | pass both | fail cov only (RSSSF rescues) | fail precision only | fail both |")
    out.append("|---|---|---|---|---|")
    for k in EDITION_CUTS:
        both = sum(1 for s in usable if covered(s, MAIN_CUT) and precise(s, k))
        cov_only = sum(1 for s in usable if not covered(s, MAIN_CUT) and precise(s, k))
        pre_only = sum(1 for s in usable if covered(s, MAIN_CUT) and not precise(s, k))
        neither = sum(1 for s in usable if not covered(s, MAIN_CUT) and not precise(s, k))
        out.append(f"| >={k} | {both} | {cov_only} | {pre_only} | {neither} |")

    out.append("\nAs a share of the badly-covered squads RSSSF would target:\n")
    bad = [s for s in usable if not covered(s, MAIN_CUT)]
    for k in EDITION_CUTS:
        r = sum(1 for s in bad if precise(s, k))
        out.append(f"- K>={k}: {r} of {len(bad)} badly-covered squads pass precision "
                   f"({r/len(bad):.0%}); the other {len(bad)-r} are unmeasurable regardless "
                   f"of coverage.")

    # ------------------------------------------------- what RSSSF actually adds
    out.append("\n### Which federations RSSSF would add\n")
    out.append("Squad counts overstate what a supplementary source buys, because one")
    out.append("federation can be rescued in several senior editions. The number that")
    out.append("matters for whether a cross-federation comparison becomes possible is")
    out.append("distinct federations added to the surviving set.\n")
    out.append("| K | federations now | federations after RSSSF | added |")
    out.append("|---|---|---|---|")
    for k in EDITION_CUTS:
        now = {s.team for s in usable if covered(s, MAIN_CUT) and precise(s, k)}
        after = {s.team for s in usable if precise(s, k)}
        out.append(f"| >={k} | {len(now)} | {len(after)} | {len(after - now)} |")
    now5 = {s.team for s in usable if covered(s, MAIN_CUT) and precise(s, 5)}
    add5 = sorted({s.team for s in usable if precise(s, 5)} - now5)
    out.append(f"\nAt K>=5 the {len(add5)} federations RSSSF would add: {', '.join(add5)}.")

    # -------------------------------------------------- who survives, structurally
    out.append("\n### What the surviving set is made of\n")
    out.append("The two filters are not independent of the thing being measured.")
    out.append("Article coverage tracks national wealth and European club presence;")
    out.append("qualification frequency tracks youth-programme investment. Both select")
    out.append("the same federations, so the intersection is not a random subsample of")
    out.append("world football -- it is close to a list of well-resourced federations.")
    out.append("Any finding computed on it is a finding about that set, and cannot")
    out.append("speak to whether youth pipelines feed senior success in general.\n")
    for gender, name in (("m", "men"), ("w", "women")):
        keep_g = [s for s in usable
                  if s.gender == gender and covered(s, MAIN_CUT) and precise(s, 5)]
        out.append(f"- {name}: {len(keep_g)} squads, "
                   f"{len({s.team for s in keep_g})} distinct federations, across "
                   f"{len({s.year for s in keep_g})} senior editions")

    # ------------------------------------------------------------- the surviving set
    out.append(f"\n## The surviving set at redlink <{MAIN_CUT:.0%}, K>=5\n")
    keep = sorted([s for s in usable if covered(s, MAIN_CUT) and precise(s, 5)],
                  key=lambda s: (s.gender, s.year, s.team))
    out.append(f"{len(keep)} squads, "
               f"{len({s.team for s in keep})} distinct federations.\n")
    out.append("| edition | federation | redlink | eds ingested | pool | share |")
    out.append("|---|---|---|---|---|---|")
    for s in keep:
        out.append(f"| {s.ed} | {s.team} | {s.redlink:.1%} | {s.n_ing} | {s.pool} | "
                   f"{s.share:.1%} |")

    out.append("\nFederations by how many of the six senior editions they survive in:\n")
    counts: dict[str, list[str]] = {}
    for s in keep:
        counts.setdefault(s.team, []).append(s.ed)
    for team, eds in sorted(counts.items(), key=lambda kv: (-len(kv[1]), kv[0])):
        out.append(f"- {team} ({len(eds)}): {', '.join(eds)}")

    out.append("\nShares appear here only to show the surviving set is not degenerate.")
    out.append("This is not a ranked table and must not be read as one -- the rows are in")
    out.append("edition-then-alphabetical order, and whether such a table can ever be")
    out.append("meaningful is still the open question.")

    text = "\n".join(out) + "\n"
    REPORTS.mkdir(exist_ok=True)
    (REPORTS / "intersection.md").write_text(text, encoding="utf-8")
    print(text)
    print(f"wrote {REPORTS / 'intersection.md'}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
